[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "advent_of_code_2024"
path = "src/main.rs"
[lib]
name = "advent_of_code_2024"
path = "src/lib.rs"

[dependencies]
